baseURL = 'https://gareth.page/'
languageCode = 'en-us'
title = 'gareth.page'
theme = 'nightfall'

[params]
author = "gareth's dev blog"
user = "hello"
hostname = "gareth.page"
footerHtml = '© 2023 Gareth George'

[[params.social]]
key = 0
name = "github"
url = "https://github.com/garethgeorge/"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/garethgeorge97"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"

